"""
Django settings for biostar_writer project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys

# directory where manage.py lives
BASE_DIR = (
    os.path.dirname(
        os.path.dirname(
            os.path.dirname(
                os.path.abspath(__file__)
            )
        )
    )
)

SECURE_CONTENT_TYPE_NOSNIFF = True  # https://docs.djangoproject.com/en/2.1/ref/middleware/#x-content-type-options
SECURE_BROWSER_XSS_FILTER = True  # https://docs.djangoproject.com/en/2.1/ref/middleware/#x-xss-protection-1-mode-block
X_FRAME_OPTIONS = 'DENY'  # https://docs.djangoproject.com/en/2.1/ref/clickjacking/

# Application definition

INSTALLED_APPS = [
    # built-in
    'django.contrib.contenttypes',
    'django.contrib.auth',  # required by REST framework
    'django.contrib.sessions',  # required for auth
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # third-party
    'rest_framework',
    'rest_framework.authtoken',  # requered by TokenAuthentication
    'background_task',

    # project
    'badges',
    'common',
    'lner',
    'posts',
    'users',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',  # required for auth
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # required for auth
    'django.middleware.csrf.CsrfViewMiddleware',  # useful, enabled by sessions
]

ROOT_URLCONF = 'biostar_writer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',  # required for auth
            ],
        },
    },
]

WSGI_APPLICATION = 'biostar_writer.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = []  # no password on this site


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

def get_env(name, default=None, strict=False, func=None):
    """Get the environment variable or return exception"""

    if strict and name not in os.environ:
        msg = "*** Required environment variable '{}' not set.".format(name)
        raise ImproperlyConfigured(msg)

    value = os.environ.get(name, default)

    if not value:
        msg = "*** Required environment variable '{}' not set and has no default value".format(
            name)
        raise ImproperlyConfigured(msg)

    if func:
        return func(value)
    else:
        # python 3 no longer has "unicode" type, it uses "str" instaed
        try:
            return unicode(value, encoding="utf-8")

        except Exception as e: 
            if sys.version_info >= (3, 0):
                return str(value)
            else:
                raise e

#
# Used in common.html_util
#
ALLOWED_TAGS = "p div br code pre h1 h2 h3 h4 hr span s sub sup b i img strong strike em underline super table thead tr th td tbody".split()
ALLOWED_STYLES = 'color font-weight background-color width height'.split()
ALLOWED_ATTRIBUTES = {
    '*': ['class', 'style'],
    'a': ['href', 'rel'],
    'img': ['src', 'alt', 'width', 'height'],
    'table': ['border', 'cellpadding', 'cellspacing'],
}
__DEFAULT_SITE_DOMAIN = 'www.lvh.me'
SITE_DOMAIN = get_env("SITE_DOMAIN", __DEFAULT_SITE_DOMAIN)


# biostar-ln specific config
MOCK_LN_CLIENT = False
