# Generated by Django 2.1.7 on 2019-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningInvoiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
