# Generated by Django 2.1.7 on 2019-12-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0002_lightninginvoicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelistcheckpoint',
            name='add_index',
        ),
        migrations.AddField(
            model_name='invoicelistcheckpoint',
            name='checkpoint_value',
            field=models.IntegerField(default=0, verbose_name='Integer value of the checkpoint (e.g. offset)'),
        ),
    ]
