# Generated by Django 2.1.7 on 2019-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0003_auto_20191224_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelistcheckpoint',
            name='comment',
            field=models.CharField(default='__DEFAULT__', max_length=255, verbose_name='Comment'),
        ),
    ]
