# Generated by Django 2.1.7 on 2019-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0004_lightningnode_rpcserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceListCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_index', models.IntegerField(default=-1, verbose_name='LN Invoice add_index')),
            ],
        ),
    ]
