# Generated by Django 2.1.7 on 2019-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0004_invoicelistcheckpoint_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelistcheckpoint',
            name='checkpoint_value',
            field=models.IntegerField(default=0, verbose_name='Integer value of the checkpoint (e.g. offset). Zero invalidates checkpoint.'),
        ),
    ]
