# Generated by Django 2.1.7 on 2019-05-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0005_invoicelistcheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelistcheckpoint',
            name='checkpoint_name',
            field=models.CharField(default='__DEFAULT__', max_length=255, verbose_name='Checkpoint name'),
        ),
        migrations.AddField(
            model_name='invoicelistcheckpoint',
            name='lightning_node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lner.LightningNode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicelistcheckpoint',
            name='add_index',
            field=models.IntegerField(default=0, verbose_name='LN Invoice add_index'),
        ),
    ]
