# Generated by Django 2.2.9 on 2019-12-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0007_add_checkpoint_name_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightninginvoice',
            name='pay_req',
            field=models.CharField(max_length=1000, verbose_name='LN Invoice pay_req'),
        ),
    ]
