# Generated by Django 2.2.9 on 2020-01-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0008_pay_req_size_to_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningInvoiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=1000, unique=True, verbose_name='LN Invoice memo')),
                ('lightning_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lner.LightningNode')),
            ],
        ),
    ]
