# Generated by Django 2.2.9 on 2020-01-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0009_lightninginvoicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightninginvoice',
            name='lightning_invoice_request',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lner.LightningInvoiceRequest'),
        ),
    ]
