# Generated by Django 2.2.9 on 2020-01-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0010_lightninginvoice_lightning_invoice_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightninginvoice',
            name='checkpoint_status',
            field=models.CharField(default='__DEFAULT__', max_length=255, verbose_name='Status'),
        ),
    ]
