# Generated by Django 2.2.9 on 2020-01-17 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0012_quick_payment_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_hash', models.CharField(default='__DEFAULT__', max_length=255, verbose_name='LN Invoice r_hash')),
                ('pay_req', models.CharField(max_length=2000, verbose_name='LN Invoice pay_req')),
                ('add_index', models.IntegerField(default=-1, verbose_name='LN Invoice add_index')),
                ('checkpoint_value', models.CharField(default='no_checkpoint', max_length=255, verbose_name='E.g. done, expired, canceled, deserialize_failure, or memo_invalid.')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=1000, unique=True, verbose_name='LN Invoice memo')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lightninginvoice',
            name='lightning_invoice_request',
        ),
        migrations.RemoveField(
            model_name='lightninginvoicerequest',
            name='lightning_node',
        ),
        migrations.AddField(
            model_name='lightningnode',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightningnode',
            name='global_checkpoint',
            field=models.IntegerField(default=-1, verbose_name='add_index of the last global checkpoint'),
        ),
        migrations.AddField(
            model_name='lightningnode',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InvoiceListCheckpoint',
        ),
        migrations.DeleteModel(
            name='LightningInvoice',
        ),
        migrations.DeleteModel(
            name='LightningInvoiceRequest',
        ),
        migrations.AddField(
            model_name='invoicerequest',
            name='lightning_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lner.LightningNode'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_request',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lner.InvoiceRequest'),
        ),
    ]
