# Generated by Django 2.2.9 on 2020-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0013_simplify_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='performed_action_id',
            field=models.IntegerField(default=-1, verbose_name='E.g. post.id'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='performed_action_type',
            field=models.CharField(default='no_action', max_length=255, verbose_name='E.g. "post"'),
        ),
    ]
