# Generated by Django 2.2.9 on 2020-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0015_verifymessageresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerequest',
            name='memo',
            field=models.CharField(max_length=1000, verbose_name='LN Invoice memo'),
        ),
    ]
