# Generated by Django 2.2.9 on 2020-02-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0016_allow_memo_duplicates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightningnode',
            old_name='identity_pubkey',
            new_name='node_name',
        ),
    ]
