# Generated by Django 2.2.10 on 2020-03-09 16:23

from django.db import migrations, models
import django.db.models.deletion
import lner.models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0018_lightningnode_qos_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lightning_node',
            field=models.ForeignKey(default=lner.models.get_first_node, on_delete=django.db.models.deletion.CASCADE, to='lner.LightningNode'),
        ),
    ]
