# Generated by Django 2.2.11 on 2020-04-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0019_invoice_lightning_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningnode',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Should this node show up in the Web UI and used in process_tasks?'),
        ),
        migrations.AlterField(
            model_name='invoicerequest',
            name='memo',
            field=models.CharField(max_length=600, verbose_name='LN Invoice memo'),
        ),
    ]
