# Generated by Django 2.2.11 on 2020-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0020_auto_20200403_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningnode',
            name='connect_ip',
            field=models.CharField(default='1.2.3.4:9735', max_length=255, verbose_name='Public IP:port of the target node'),
        ),
        migrations.AddField(
            model_name='lightningnode',
            name='connect_tor',
            field=models.CharField(default='abczyx123.onion:9735', max_length=255, verbose_name='Public onion:port of the target node'),
        ),
        migrations.AddField(
            model_name='lightningnode',
            name='is_tor',
            field=models.BooleanField(default=True, verbose_name='Should this node receive open channels through Tor?'),
        ),
    ]
