# Generated by Django 2.2.11 on 2020-04-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0021_auto_20200409_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningnode',
            name='node_key',
            field=models.CharField(db_index=True, default='Unknown', max_length=255, unique=True, verbose_name='LN Identity Pubkey'),
        ),
        migrations.AlterField(
            model_name='lightningnode',
            name='node_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='LN Node Name'),
        ),
    ]
