# Generated by Django 2.2.11 on 2020-04-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0022_auto_20200410_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightningnode',
            name='node_key',
            field=models.CharField(db_index=True, default='Unknown', max_length=255, verbose_name='LN Identity Pubkey'),
        ),
    ]
