# Generated by Django 2.2.11 on 2020-05-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0022_auto_20200410_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAwardResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_successful', models.BooleanField(verbose_name="Is message valid against it's signature?")),
                ('failure_message', models.CharField(default='', max_length=255, verbose_name='The failure message to report back to the user')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
