# Generated by Django 2.1.7 on 2019-12-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191210_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsub',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postpreview',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replytoken',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'Question'), (1, 'Answer'), (2, 'Meta'), (3, 'Comment')], db_index=True),
        ),
        migrations.AlterField(
            model_name='postpreview',
            name='type',
            field=models.IntegerField(choices=[(0, 'Question'), (1, 'Answer'), (2, 'Meta'), (3, 'Comment')]),
        ),
    ]
