# Generated by Django 2.1.7 on 2019-12-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191215_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSub',
        ),
    ]
