# Generated by Django 2.2.11 on 2020-04-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postpreview_parent_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpreview',
            name='memo',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
