# Generated by Django 2.2.11 on 2020-05-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='ammount',
        ),
        migrations.AddField(
            model_name='bounty',
            name='amt',
            field=models.IntegerField(default=-1, verbose_name='amount in sats of the total award for winning the bounty'),
        ),
        migrations.AlterField(
            model_name='bountyaward',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='post_id which Answer post won the awarded'),
        ),
    ]
