# Generated by Django 2.2.11 on 2020-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_auto_20200503_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='activation_time',
            field=models.DateTimeField(verbose_name='activation_time is when the bounty became active most recently'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='award_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='award_time is when the winner was announced'),
        ),
    ]
