# Generated by Django 2.2.10 on 2020-05-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_auto_20200503_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='award_time',
            field=models.DateTimeField(null=True, verbose_name='award_time is when the winner was announced'),
        ),
    ]
