# Generated by Django 2.2.11 on 2020-05-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200403_1729'),
        ('bounty', '0003_auto_20200509_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyaward',
            name='bounty_id',
        ),
        migrations.RemoveField(
            model_name='bountyaward',
            name='post_id',
        ),
        migrations.AddField(
            model_name='bountyaward',
            name='bounty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bounty.Bounty', verbose_name='bounty which bounty is awarded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bountyaward',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='post which Answer post won the awarded'),
            preserve_default=False,
        ),
    ]
