# Generated by Django 2.1.7 on 2019-03-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lner', '0002_lightninginvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightninginvoice',
            name='add_index',
            field=models.IntegerField(default=-1, verbose_name='LN Invoice add_index'),
        ),
        migrations.AddField(
            model_name='lightninginvoice',
            name='r_hash',
            field=models.CharField(default='__DEFAULT__', max_length=255, verbose_name='LN Invoice r_hash'),
        ),
        migrations.AlterField(
            model_name='lightninginvoice',
            name='pay_req',
            field=models.CharField(max_length=255, verbose_name='LN Invoice pay_req'),
        ),
    ]
