# Generated by Django 2.2.10 on 2020-02-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('badges', '0002_badge_is_fake_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
