# Generated by Django 2.2.11 on 2020-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_award_to_user_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_fake_test_data',
            field=models.BooleanField(default=False),
        ),
    ]
